# Generated by Django 5.2.11 on 2026-04-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_filaprato_delivered_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="prato",
            name="estoque",
            field=models.IntegerField(default=100),
        ),
    ]
