# Generated by Django 5.2.11 on 2026-04-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_prato_estoque"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filaprato",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente"),
                    ("EM_PRODUCAO", "Em Producao"),
                    ("FINALIZADO", "Finalizado"),
                    ("RETIRADO", "Retirado"),
                    ("CANCELADO", "Cancelado"),
                ],
                default="PENDENTE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente"),
                    ("PRODUCAO", "Producao"),
                    ("FINALIZADO", "Finalizado"),
                    ("RETIRADO", "Retirado"),
                    ("CANCELADO", "Cancelado"),
                ],
                db_index=True,
                default="PENDENTE",
                max_length=20,
            ),
        ),
    ]
